DROP TABLE [dbo].[Products];
CREATE TABLE [dbo].[Products] 
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[TITLE]	NVARCHAR(30) UNIQUE NULL,
	[DESCRIPTION] NVARCHAR(50) NULL,
	[PRICE] DECIMAL(10,2) NULL
)